name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Debug Webhook URL
        run: 'echo "Webhook URL: ${{ secrets.DISCORD_WEBHOOK }}"'
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Test Success
        uses: stegzilla/discord-notify@v4
        if: ${{ success() }}
        with:
          title: Successful Tagging and Deployment
          message: Success!
          colour: "#00FF00"
          username: javiercoronadonarvaez
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: stegzilla/discord-notify@v4
        if: ${{ failure() }}
        with:
          title: Unsuccessful Tagging and Deployment
          message: Failure!
          colour: "#FF0000"
          username: javiercoronadonarvaez
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

      # - name: Send Test Success Notification
      #   if: ${{ success() }}
      #   run: |
      #     curl -X POST -H "Content-Type: application/json" \
      #     -d "{\"content\": \"Test Succeeded!\"}" \
      #     ${{ secrets.DISCORD_WEBHOOK }}
      # - name: Send Test Failure Notification
      #   if: ${{ failure() }}
      #   run: |
      #     curl -X POST -H "Content-Type: application/json" \
      #     -d "{\"content\": \"Test Failed!\"}" \
      #     ${{ secrets.DISCORD_WEBHOOK }}
